### PR TITLE
Enable release action/rules for EL8 

### PR DESCRIPTION
**Pull request by punkrokk**
* enable EL8 rules

### CODE REVIEW

**Comment by arm4b** [comment]
I looked deeper and here is why EL8 wasn't changed.
We'll need another change here: 
https://github.com/StackStorm/st2cd/blob/fdde9c37b211ef004cc2a9a2a32edf5fd1714552/actions/st2_prep_release_cd_rules.meta.yaml#L33-L34

I must thank @blag for adding ^^ those `TODO` code comment hints :+1:

**Comment by punkrokk** [comment]
@armab Resolved your change request.

**Review by arm4b — APPROVED** [review]
LGTM.

Even though Title and Description for this Github PR could have more details.

This always helps when looking back in history while searching for some similar issues.

**Comment by arm4b** [comment]
Enable EL8 rules, missed updating by the `v3.2.0` release automation.

See the commit which missed it https://github.com/StackStorm/st2cd/commit/fdde9c37b211ef004cc2a9a2a32edf5fd1714552

**Pull request merged**
