### PR TITLE
Fix trigger type for librato event

### PR DESCRIPTION
**Pull request by manasdk**
Well obviously actiontrigger is the wrong trigger type

### CODE REVIEW

**Comment by manasdk** [comment]
@DoriftoShoes @Kami 

Btw, what is the action this rule triggers even supposed to be doing? Should this annotation be added at the end of a release so after finalize or something? Likely would need a bit more work.

We could add at start of release also like the rule is setup to do but that means it would miss out on patches.

**Comment by manasdk** [comment]
On closer inspection I am not sure what this is doing really. The way I have changed it every commit to a release branch will lead to an annotation. Previous rule definition was just wrong.

**Comment by manasdk** [comment]
Will go ahead and merge for now.

**Comment by Kami** [comment]
@manasdk Yep - it should send an annotation to librato on release.

This way we can cross reference other metrics to release, etc.

It definitely worked in the (distant) part, but yeah this have changes around and this rule was probably never updated.

**Pull request merged**
