### PR TITLE
remove old promote action

### PR DESCRIPTION
**Pull request by manasdk**

### CODE REVIEW

**Comment by m4dcoder** [comment]
i believe there's a chatops alias for this action as well.

**Comment by emedvedev** [comment]
There's an alias `promote_package.yaml`. Just make it work with the new action (should be easy, input is almost the same), and the old one can burn. :fire:

**Comment by manasdk** [comment]
@emedvedev @m4dcoder Unfortunately same input and almost the same are not the same thing :(

It might be best to rewrite this alias. It will take me a while.

**Comment by manasdk** [comment]
I decided to take the easy way out and moved promote_package https://github.com/StackStorm/st2ci/pull/8

@m4dcoder I know this is contrary to your opinion but it is the easier option. Rather rewrite the alias but I am not motivated to do that right now.

**Pull request merged**
