### PR TITLE
Implement workflow to cleanup volumes

### PR DESCRIPTION
**Pull request by m4dcoder**

### CODE REVIEW

**Comment by estee-tew** [comment]
https://stackstorm.slack.com/archives/stackstorm/p1455048584006124

**Comment by DoriftoShoes** [comment]
+1

**Comment by lakshmi-kannan** [comment]
I actually have no idea how this will be wired. I'll merge it and let @m4dcoder deal with it when he's back.

**Comment by estee-tew** [comment]
https://stackstorm.slack.com/archives/stackstorm/p1455049569006141

**Pull request merged**
