### PR TITLE
Re-enable bats tests

### PR DESCRIPTION
**Pull request by Kami**
This pull request re-enables bats tests.

### CODE REVIEW

**Comment by Kami** [comment]
It looks like one test is still failing:

```bash
not ok 37 rule status works
# (from function `assert_output' in file docs/../test_helpers/bats-assert/src/assert.bash, line 239,
#  in test file docs/test_sample_rule_with_webhook.bats, line 99)
#   `assert_output "bar"' failed
# 
# -- output differs --
# expected : bar
# actual   : null
# --
# 
ok 38 rule deletion works and is idempotent (with an error message)"
```

**Comment by Kami** [comment]
It looks like it's referencing an invalid environment variable, it should be ``ST2_AUTH_TOKEN`` and not ``TOKEN`` - https://github.com/StackStorm/st2cd/blob/cf834ad2782335893230bdc6407b82cf1beb10e0/actions/workflows/st2_e2e_tests.yaml#L38.

I'll try that.

EDIT: Looks like it's related to this commit - https://github.com/StackStorm/st2tests/commit/87b33e324a41ed6f68b5b33363e83372fb8d2f7a.

**Comment by Kami** [comment]
It looks like my change worked - https://github.com/StackStorm/st2tests/commit/8135809941f5dca6e6edbde6f15ea5d50233e166

```bash
Child execution (task=run_e2e_tests) 5cdc28e8fa30714846d07d93 has started.

Child execution (task=run_docs_tests) 5cdc2992fa30714846d07d9f has started.

1..38
ok 1 st2 version works
ok 2 st2 usage works
ok 3 st2 help works
ok 4 action list for core.local and core.remote action
ok 5 action get core.http works
ok 6 execution list includes the core.local 'date' that was just run
ok 7 sensor list works
ok 8 trigger list works
ok 9 trigger get works
ok 10 core.remote action works
ok 11 packs are not present before a clean install
ok 12 multiple packs can be installed from repo
ok 13 list actions in libcloud pack
ok 14 list actions in consul pack
ok 15 multiple packs can be removed
ok 16 no actions in libcloud pack
ok 17 no actions in consul pack
ok 18 packs can be downloaded using packs.download
ok 19 can run packs.setup_virtualenv for a pack downloaded in previous step
ok 20 packs register registers all packs
ok 21 pack install with no config
ok 22 pack reinstall with no config
ok 23 key-value triggers exist
ok 24 create key-value works
ok 25 update key-value works
ok 26 key-value value change works
ok 27 delete key-value key
ok 28 load key values from JSON file
ok 29 list key values in JSON
ok 30 delete keys by prefix
ok 31 delete key-value with numeric key
ok 32 key-value operations with expiries
ok 33 rule creation works and is idempotent (with an error message)
ok 34 rule get works
ok 35 rule list works
ok 36 rule disable/enable works
ok 37 rule status works
ok 38 rule deletion works and is idempotent (with an error message)

Child execution (task=run_docs_tests) 5cdc2992fa30714846d07d9f has finished (status=succeeded).
Child execution (task=run_e2e_tests) 5cdc28e8fa30714846d07d93 has started.

Child execution (task=run_cli_tests) 5cdc2a76fa30714846d07da2 has started.

1..30
ok 1 load command works and is idempotent
ok 2 SETUP: reinstall the examples pack and set actionrunner.stream_output to True
ok 3 st2 execution tail works correctly for simple actions
ok 4 st2 execution tail works correctly for action chain workflows
ok 5 st2 execution tail command works correctly for Mistral workflows
ok 6 st2 execution tail command works correctly for Orquesta workflows
ok 7 st2 execution list include attributes works
ok 8 st2 execution list include nonexistent attribute errors
ok 9 st2 action list include attributes works
ok 10 st2 action list include nonexistent attribute errors
ok 11 default note in execution list
ok 12 default note in trace list
ok 13 default note in trigger instance list
ok 14 default note in rule list
ok 15 default note in rule enforcement list
ok 16 default note in key/value list
ok 17 note when action execution limit is 1
ok 18 note when trace limit is 1
ok 19 note when trigger instance limit is 1
ok 20 note when rule limit is 1
ok 21 note when rule enforcement limit is 1
ok 22 no note on action execution list with JSON/YAML output
ok 23 no note on trace list with JSON/YAML output
ok 24 no note on trigger instance list with JSON/YAML output
ok 25 no note on rule list with JSON/YAML output
ok 26 no note on rule enforcement list with JSON/YAML output
ok 27 no note on key/value list with JSON/YAML output
ok 28 packs.setup_virtualenv without python3 flags works and defaults to Python 2 # skip Python 3 binary not found, skipping tests
ok 29 packs.setup_virtualenv with python3 flag works # skip Python 3 binary not found, skipping tests
ok 30 python3 imports work correctly # skip Python 3 binary not found, skipping tests

Child execution (task=run_cli_tests) 5cdc2a76fa30714846d07da2 has finished (status=succeeded).
Child execution (task=run_e2e_tests) 5cdc28e8fa30714846d07d93 has started.

Child execution (task=run_chatops_tests) 5cdc2b76fa30714846d07da5 has started.

1..7
ok 1 StackStorm's client connection
ok 2 npm directory exists
ok 3 some StackStorm aliases are enabled
ok 4 chatops.notify rule exists
ok 5 hubot help command works
ok 6 chatops.post_message execution and receive status works
ok 7 complete request-response flow

Child execution (task=run_chatops_tests) 5cdc2b76fa30714846d07da5 has finished (status=succeeded).

Chatops tests still appear to be broken (task=run_chatops_e2e_tests) so for now, I will go ahead and only enable bats doc, cli and basic chatops tests and let you figure out run_chatops_e2e_tests.
```

**Comment by Kami** [comment]
Also needed this fix - https://github.com/StackStorm/st2tests/commit/3509eb1.

Previous setup version also wasn't 100% correct, since we only want to skip second and third test in such scenario and not the first one (we still want to run the first one).

**Comment by Kami** [comment]
To sum up the issue with random test timeouts and failures related to RabbitMQ we started seeing recently.

It turns out the issue is indeed related to wrong hostname being set on the server. Our ``set_hostname`` action was broken and not fully correct on RHEL - it used ``hostname`` command to set hostname, but it didn't write it to ``/etc/hostname`` so it wasn't persisted across the reboots (and we perform a server reboot in our workflow immediately after setting the hostname).

The "weird" thing is that issue didn't always appear. I believe that's probably related to changed cloud-init behavior. It looks like sometimes preserve_hostname option defaults to true and sometimes to false.

In any case, changes in this PR fix that - we now correctly set hosname and preserve it across the server restarts.

**Comment by arm4b** [comment]
Feels good to see the root cause investigation & fix for EL7 hostnames :+1:

**Pull request merged**
