### PR TITLE
Update pypi upload API

### PR DESCRIPTION
**Pull request by humblearner**
Thanks @m4dcoder for fix.

### CODE REVIEW

**Comment by arm4b** [comment]
Can you clarify in the first message details and background about the issue?

Does it also mean release management servers are able to deploy package to pypi & are fixed or it's a different issue?

**Comment by m4dcoder** [comment]
This change only fix the script to upload to packages to pypi. It does not mean the ubuntu-build servers are fixed. Those servers required the python to be upgrade to latest 2.7.x version for this script to run.

**Comment by arm4b** [comment]
@m4dcoder Thanks for clarification.

If we're not going to fix the `ubuntu-build` servers (python issue) in nearest time, let's please document it as Issue then so next release manager will be aware of it.

**Review by Kami — APPROVED** [review]

**Comment by humblearner** [comment]
Updated both `ubuntu-build002` and `ubuntu-build003` from 2.7.6 to 2.7.14 for this script to work

**Pull request merged**
