### PR TITLE
Tag st2-docker with release version

### LINKED ISSUE #305: Tag st2-docker repo after release packages are available
# Overview

Notes from a quick discussion with @m4dcoder. As work starts, more details will be added here.

This feature is scheduled to be available for StackStorm `2.5.0`.

# References

https://github.com/StackStorm/discussions/wiki/Release-Process

# Description

Add a step in `st2cd.st2_finalize_release` workflow, tag `st2-docker` with version number (e.g. `v2.4.1`) of the ST2 build that is being released. Base off of https://github.com/StackStorm/st2cd/blob/master/actions/st2_tag_release.sh

# Questions

 - [ ] Determine how we can automate testing of the docker images. Something like step 3 or 6 in the release process. Create `st2 run st2ci.st2_dkr_e2e_test`.
 - [ ] Determine how to roll back the docker images if something doesn't work.

### PR DESCRIPTION
**Pull request by warrenvw**
Closes #305.

Are the following blockers to this PR?
 - Determine how we can automate testing of the docker images. Something like step 3 or 6 in the release process. Create `st2 run st2ci.st2_dkr_e2e_test`.
 - Determine how to roll back the docker images if something doesn't work.

### CODE REVIEW

**Comment by warrenvw** [comment]
Regarding the above two points:

 - I agree, we should automate testing of the docker images. Should this be done using the `st2-docker` CI so that this can be done on every build/deploy, not just when we release a new version of st2?
 - As it exists today, once a tag is pushed in the `st2-docker` github repo, the image will be built and deployed to docker hub. We can rebuild images and deploy them as necessary, although currently this is a manual process.

Please give the code in this PR a quick look to see if it's headed the right direction.

**Review by arm4b — APPROVED** [review]
:+1:

**Comment by arm4b** [comment]
The only confusing thing now is naming for `st2_tag_release`, since it's used not only to create tag for st2 repo, but is more universal now.

**Comment by warrenvw** [comment]
Yeah, the name is less than ideal. I guess I thought it's okay because the description of the script in `st2_tag_release.meta.yaml` is "Tag release on a st2 project". Seemed to imply more than one project.

Okay.. I can change the script name to `tag_release` (keeping in mind some of the defaults defined in the YAML file refer to "fork" `StackStorm`)?

**Pull request merged**
